#if !canImport(ObjectiveC)
import XCTest

extension JSONParserTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__JSONParserTests = [
        ("testCharSeqUnicode", testCharSeqUnicode),
        ("testCharSeqUnicodeMultiple", testCharSeqUnicodeMultiple),
        ("testJSON", testJSON),
        ("testJSONSpeed", testJSONSpeed),
        ("testString", testString),
        ("testUnicode", testUnicode),
    ]
}

extension ParserCombinatorsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ParserCombinatorsTests = [
        ("testAccept", testAccept),
        ("testCalculator", testCalculator),
        ("testCapturing", testCapturing),
        ("testCapturing2", testCapturing2),
        ("testCapturing3", testCapturing3),
        ("testChainLeft", testChainLeft),
        ("testChainRight", testChainRight),
        ("testCommitOr", testCommitOr),
        ("testCommitOrLongerDifferent", testCommitOrLongerDifferent),
        ("testCommitOrLongerSame", testCommitOrLongerSame),
        ("testEndOfInput", testEndOfInput),
        ("testFilter", testFilter),
        ("testFollowedBy", testFollowedBy),
        ("testLeftRecursion", testLeftRecursion),
        ("testLiteral", testLiteral),
        ("testMap", testMap),
        ("testMapValue", testMapValue),
        ("testNotFollowedBy", testNotFollowedBy),
        ("testOpt", testOpt),
        ("testOr", testOr),
        ("testOrErrorFirst", testOrErrorFirst),
        ("testOrErrorSecond", testOrErrorSecond),
        ("testOrFailure", testOrFailure),
        ("testOrFirstSuccess", testOrFirstSuccess),
        ("testOrLongerDifferent", testOrLongerDifferent),
        ("testOrLongerSameFirst", testOrLongerSameFirst),
        ("testOrLongerSameSecond", testOrLongerSameSecond),
        ("testRecursive", testRecursive),
        ("testRecursive2", testRecursive2),
        ("testRepError", testRepError),
        ("testRepMinMax", testRepMinMax),
        ("testRepMinNoMax", testRepMinNoMax),
        ("testRepNoMinNoMax", testRepNoMinNoMax),
        ("testRepSepMinMax", testRepSepMinMax),
        ("testRepSepMinNoMax", testRepSepMinNoMax),
        ("testRepSepNoMinNoMax", testRepSepNoMinNoMax),
        ("testRepSepZeroMax", testRepSepZeroMax),
        ("testRepZeroMax", testRepZeroMax),
        ("testSeq", testSeq),
        ("testSeq3", testSeq3),
        ("testSeq4", testSeq4),
        ("testSeq5", testSeq5),
        ("testSeqIgnoreLeft", testSeqIgnoreLeft),
        ("testSeqIgnoreRight", testSeqIgnoreRight),
        ("testSeqTuple", testSeqTuple),
        ("testSeqUnit", testSeqUnit),
        ("testSkipUntil", testSkipUntil),
        ("testTuples", testTuples),
    ]
}

extension PatternsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PatternsTests = [
        ("testCompilation", testCompilation),
    ]
}

extension PositionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PositionTests = [
        ("testStringLongDescription", testStringLongDescription),
        ("testStringsLongDescription", testStringsLongDescription),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(JSONParserTests.__allTests__JSONParserTests),
        testCase(ParserCombinatorsTests.__allTests__ParserCombinatorsTests),
        testCase(PatternsTests.__allTests__PatternsTests),
        testCase(PositionTests.__allTests__PositionTests),
    ]
}
#endif
